-- echasnovski/mini.nvim
local M = {}

function M.setup(palette, config, utilities, groups)
  local styles = config.options.styles
  return {
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { link = "NormalFloat" },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { bg = groups.panel, bold = styles.bold },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniDepsChangeAdded = { fg = groups.git_add },
    MiniDepsChangeRemoved = { fg = groups.git_delete },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffText" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { fg = groups.git_add, bg = groups.git_add, blend = 20 },
    MiniDiffOverChange = { fg = groups.git_change, bg = groups.git_change, blend = 20 },
    MiniDiffOverContext = { bg = palette.bg_second },
    MiniDiffOverDelete = { fg = groups.git_delete, bg = groups.git_delete, blend = 20 },
    MiniDiffSignAdd = { fg = groups.git_add },
    MiniDiffSignChange = { fg = groups.git_change },
    MiniDiffSignDelete = { fg = groups.git_delete },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { link = "CursorLine" },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { fg = palette.fg },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { fg = palette.purple_lite, bg = groups.panel, bold = styles.bold },
    MiniHipatternsFixme = { fg = palette.bg_main, bg = groups.error, bold = styles.bold },
    MiniHipatternsHack = { fg = palette.bg_main, bg = groups.warn, bold = styles.bold },
    MiniHipatternsNote = { fg = palette.bg_main, bg = groups.info, bold = styles.bold },
    MiniHipatternsTodo = { fg = palette.bg_main, bg = groups.hint, bold = styles.bold },
    MiniIconsAzure = { fg = palette.aqua_lite },
    MiniIconsBlue = { fg = palette.blue_lite },
    MiniIconsCyan = { fg = palette.aqua_lite },
    MiniIconsGreen = { fg = palette.green_lite },
    MiniIconsGrey = { fg = palette.gray },
    MiniIconsOrange = { fg = palette.orange_lite },
    MiniIconsPurple = { fg = palette.purple_lite },
    MiniIconsRed = { fg = palette.red_lite },
    MiniIconsYellow = { fg = palette.yellow_lite },
    MiniIndentscopeSymbol = { fg = palette.fg4 },
    MiniIndentscopeSymbolOff = { fg = palette.yellow_lite },
    MiniJump = { sp = palette.yellow_lite, undercurl = true },
    MiniJump2dDim = { fg = palette.gray },
    MiniJump2dSpot = { fg = palette.yellow_lite, bold = styles.bold, nocombine = true },
    MiniJump2dSpotAhead = { fg = palette.aqua_lite, bg = palette.bg_second, nocombine = true },
    MiniJump2dSpotUnique = { fg = palette.purple_lite, bold = styles.bold, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { bg = groups.panel },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { link = "CursorLine" },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { fg = palette.aqua_lite },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { bg = groups.panel, bold = styles.bold },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { fg = palette.gray },
    MiniStarterHeader = { link = "Title" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "WarningMsg" },
    MiniStarterSection = { fg = palette.purple_lite },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStatuslineDevinfo = { fg = palette.gray, bg = palette.bg3 },
    MiniStatuslineFileinfo = { link = "MiniStatuslineDevinfo" },
    MiniStatuslineFilename = { fg = palette.fg4, bg = palette.bg_second },
    MiniStatuslineInactive = { link = "MiniStatuslineFilename" },
    MiniStatuslineModeCommand = { fg = palette.bg_main, bg = palette.red_lite, bold = styles.bold },
    MiniStatuslineModeInsert = { fg = palette.bg_main, bg = palette.aqua_lite, bold = styles.bold },
    MiniStatuslineModeNormal = { fg = palette.bg_main, bg = palette.purple_lite, bold = styles.bold },
    MiniStatuslineModeOther = { fg = palette.bg_main, bg = palette.purple_lite, bold = styles.bold },
    MiniStatuslineModeReplace = { fg = palette.bg_main, bg = palette.green_dark, bold = styles.bold },
    MiniStatuslineModeVisual = { fg = palette.bg_main, bg = palette.purple_lite, bold = styles.bold },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = { fg = palette.fg, bg = palette.bg3, bold = styles.bold },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { fg = palette.gray, bg = groups.panel },
    MiniTablineModifiedCurrent = { fg = palette.bg3, bg = palette.fg, bold = styles.bold },
    MiniTablineModifiedHidden = { fg = groups.panel, bg = palette.gray },
    MiniTablineModifiedVisible = { fg = groups.panel, bg = palette.fg },
    MiniTablineTabpagesection = { link = "Search" },
    MiniTablineVisible = { fg = palette.fg, bg = groups.panel },
    MiniTestEmphasis = { bold = styles.bold },
    MiniTestFail = { fg = palette.red_lite, bold = styles.bold },
    MiniTestPass = { fg = palette.aqua_lite, bold = styles.bold },
    MiniTrailspace = { bg = palette.red_lite },
  }
end

return M
