local M = {}

function M.setup(palette, config, utilities, groups)
  local styles = config.options.styles

  return {
    ["@attribute.diff"] = { fg = palette.orange_lite },
    ["@boolean"] = { fg = palette.purple_lite, bold = styles.bold },
    ["@class"] = { fg = palette.yellow_lite, bold = styles.bold },
    ["@conditional"] = { fg = palette.red_lite, italic = true },
    ["@field"] = { fg = palette.blue_lite },
    ["@include"] = { fg = palette.aqua_lite, bold = styles.bold },
    ["@interface"] = { fg = palette.yellow_dark, italic = true },
    ["@macro"] = { fg = palette.purple_lite, bold = styles.bold },
    ["@method"] = { fg = palette.green_dark },
    ["@namespace"] = { fg = palette.fg1, italic = true },
    ["@number"] = { fg = palette.purple_lite },
    ["@parameter"] = { fg = palette.blue_lite, italic = styles.italic },
    ["@preproc"] = { fg = palette.red_dark, bold = styles.bold },
    ["@punctuation"] = { fg = palette.orange_lite },
    ["@punctuation.bracket"] = { link = "@punctuation" },
    ["@punctuation.delimiter"] = { link = "@punctuation" },
    ["@punctuation.special"] = { link = "@punctuation" },
    ["@regexp"] = { fg = palette.green_lite },
    ["@repeat"] = { fg = palette.red_lite },
    ["@storageclass"] = { fg = palette.blue_dark, bold = styles.bold },
    ["@symbol"] = { fg = palette.blue_lite },
    ["@text"] = { fg = palette.fg },
    ["@text.danger"] = { fg = palette.red_lite, bold = styles.bold },
    ["@text.diff.add"] = { fg = palette.green_lite, bg = palette.green_dark, blend = 20 },
    ["@text.diff.delete"] = { fg = palette.red_lite, bg = palette.red_dark, blend = 20 },
    ["@text.emphasis"] = { italic = styles.italic },
    ["@text.environment"] = { fg = palette.aqua_dark },
    ["@text.environment.name"] = { fg = palette.yellow_lite, bold = styles.bold },
    ["@text.math"] = { fg = palette.orange_lite },
    ["@text.note"] = { fg = palette.aqua_lite },
    ["@text.strike"] = { strikethrough = true, fg = palette.gray },
    ["@text.strong"] = { bold = styles.bold, fg = palette.fg },
    ["@text.title"] = { fg = groups.h1, bold = styles.bold },
    ["@text.title.1.markdown"] = { fg = groups.h1, bold = styles.bold },
    ["@text.title.1.marker.markdown"] = { fg = palette.red_lite },
    ["@text.title.2.markdown"] = { fg = groups.h2, bold = styles.bold },
    ["@text.title.2.marker.markdown"] = { fg = palette.yellow_lite },
    ["@text.title.3.markdown"] = { fg = groups.h3, bold = styles.bold },
    ["@text.title.3.marker.markdown"] = { fg = palette.green_lite },
    ["@text.title.4.markdown"] = { fg = groups.h4, bold = styles.bold },
    ["@text.title.4.marker.markdown"] = { fg = palette.aqua_lite },
    ["@text.title.5.markdown"] = { fg = groups.h5, bold = styles.bold },
    ["@text.title.5.marker.markdown"] = { fg = palette.blue_lite },
    ["@text.title.6.markdown"] = { fg = groups.h6, bold = styles.bold },
    ["@text.title.6.marker.markdown"] = { fg = palette.purple_lite },
    ["@text.underline"] = { underline = true, fg = palette.fg1 },
    ["@text.uri"] = { fg = palette.purple_lite, underline = true },
    ["@text.warning"] = { fg = palette.yellow_lite, bold = styles.bold },
    ["@todo"] = { fg = palette.yellow_dark, bg = palette.bg_third, bold = styles.bold, italic = true },
    ["@none"] = { bg = palette.none, fg = palette.none },
    ["@variable"] = { fg = palette.fg1 },
    ["@variable.builtin"] = { fg = palette.orange_lite, bold = styles.bold },
    ["@variable.parameter"] = { fg = palette.red_lite },
    ["@variable.parameter.builtin"] = { fg = palette.blue_lite, italic = true, bold = styles.bold },
    ["@variable.member"] = { fg = palette.blue_lite },
    ["@constant"] = { fg = palette.purple_lite },
    ["@constant.builtin"] = { fg = palette.orange_lite, bold = styles.bold },
    ["@constant.macro"] = { fg = palette.aqua_lite },
    ["@module"] = { fg = palette.fg1 },
    ["@module.builtin"] = { fg = palette.fg1, bold = styles.bold },
    ["@label"] = { link = "Label" },
    ["@string"] = { fg = palette.green_lite },
    ["@string.regexp"] = { fg = palette.aqua_dark },
    ["@string.escape"] = { fg = palette.aqua_dark },
    ["@string.special.url"] = { fg = palette.purple_lite },
    ["@type"] = { fg = palette.yellow_lite },
    ["@type.builtin"] = { fg = palette.yellow_lite, bold = styles.bold },
    ["@type.definition"] = { fg = palette.yellow_lite, bold = styles.bold },
    ["@type.qualifier"] = { fg = palette.yellow_lite },
    ["@attribute"] = { fg = palette.aqua_lite },
    ["@attribute.builtin"] = { fg = palette.aqua_lite, bold = styles.bold },
    ["@property"] = { fg = palette.blue_lite },
    ["@function"] = { fg = palette.green_dark },
    ["@function.call"] = { link = "@function" },
    ["@function.builtin"] = { fg = palette.orange_lite },
    ["@function.method"] = { link = "@function" },
    ["@function.method.call"] = { link = "@function.method" },
    ["@function.macro"] = { fg = palette.purple_lite },
    ["@constructor"] = { fg = palette.orange_dark },
    ["@keyword"] = { fg = palette.red_lite },
    ["@keyword.operator"] = { fg = palette.red_lite },
    ["@keyword.function"] = { fg = palette.red_lite },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.storage"] = { link = "StrongCalss" },
    ["@keyword.repeat"] = { fg = palette.red_lite },
    ["@keyword.return"] = { fg = palette.red_lite },
    ["@keyword.debug"] = { fg = palette.purple_dark },
    ["@keyword.exception"] = { fg = palette.red_lite },
    ["@keyword.conditional"] = { fg = palette.red_lite },
    ["@keyword.conditional.ternary"] = { fg = palette.red_dark },
    ["@keyword.directive"] = { fg = palette.aqua_lite },
    ["@keyword.directive.define"] = { fg = palette.aqua_lite, bold = styles.bold },
    ["@punctuation.delimiter"] = { fg = palette.orange_lite },
    ["@punctuation.bracket"] = { fg = palette.orange_lite },
    ["@punctuation.special"] = { fg = palette.orange_lite },
    ["@comment"] = { fg = palette.gray },
    ["@comment.error"] = { fg = palette.red_lite },
    ["@comment.warning"] = { fg = palette.yellow_lite },
    ["@comment.todo"] = { fg = palette.yellow_lite, bg = palette.bg_second, bold = styles.bold },
    ["@comment.hint"] = { fg = palette.green_lite, bg = palette.bg_second },
    ["@comment.info"] = { fg = palette.blue_lite, bg = palette.bg_second },
    ["@comment.note"] = { fg = palette.aqua_lite, bg = palette.bg_second },
    ["@markup.heading"] = { fg = palette.green_lite, bold = styles.bold },
    ["@markup.link"] = { fg = palette.blue_lite },
    ["@markup.link.url"] = { fg = palette.purple_lite, underline = true },
    ["@markup.list"] = { fg = palette.orange_dark },
    ["@markup.raw.delimiter.markdown"] = { fg = palette.gray },
    ["@diff.plus"] = { fg = palette.green_lite, bg = palette.bg_main },
    ["@diff.minus"] = { fg = palette.red_lite, bg = palette.bg_main },
    ["@diff.delta"] = { bg = palette.yellow_lite, blend = 20 },
    ["@tag.attribute"] = { fg = palette.blue_lite },
    ["@tag.delimiter"] = { fg = palette.orange_lite },
    ["@conceal.markdown"] = { fg = palette.blue_lite },
  }
end

return M
